### ISSUE TITLE
Selecting lexicalized concept only from a designated <div>

### ISSUE THREAD

**Issue by jinzhao3611** [jinzhao3611/umr-annotation-tool#2]
On page sentlevel, I am currently using [onselectionchange](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onselectionchange) to capture the selected lexicalized concept. Users can select a word token from anywhere on the page, however, we should only allow people to select from the \#sentence div.

**Comment by Konic-NLP** [comment]
fixed. I set the condition according to the DOM of the 'annotation' area while the method is super silly, I still insist that converting the selection to the input of the corresponding index of the token.
